### PR TITLE
Feat/navbar integration

### PR DESCRIPTION
**Pull request by Sahil2004**

### CODE REVIEW

**Comment by sohamjaiswal** [comment]
good shit, just a few tweaks needed 

image
put these in a position fixed, display flex, justify-content space between div

image
put a media query for this resolution so that the text does not get cut 

image
pressing the link to the page while already at the page does not remove the overlay, add a check that if link path = goto path, then remove overlay

**Comment by sohamjaiswal** [comment]
image

also align these, header would get aligned with a display flex align-items center

figure out how to align the bottom divs

**Review by sohamjaiswal — CHANGES_REQUESTED** [review]
fix the shit in the comments above

**Comment by Sahil2004** [comment]
> image
pressing the link to the page while already at the page does not remove the overlay, add a check that if link path = goto path, then remove overlay

I think this needs an active class and not redirecting because it is not in the design itself. So shall I add both (active class and closing on clicking) or just active class (as in the design)?

**Comment by sohamjaiswal** [comment]
> > image
> > pressing the link to the page while already at the page does not remove the overlay, add a check that if link path = goto path, then remove overlay
> 
> I think this needs an active class and not redirecting because it is not in the design itself. So shall I add both (active class and closing on clicking) or just active class (as in the design)?

I think just removing the class will fuck up your nav animation, but if you can find an elegant way to do it then I would rather have you just removing the overlay active class instead as that would be a more optimized approach

**Comment by Sahil2004** [comment]
> > > image
> > > pressing the link to the page while already at the page does not remove the overlay, add a check that if link path = goto path, then remove overlay
> > 
> > 
> > I think this needs an active class and not redirecting because it is not in the design itself. So shall I add both (active class and closing on clicking) or just active class (as in the design)?
> 
> I think just removing the class will fuck up your nav animation, but if you can find an elegant way to do it then I would rather have you just removing the overlay active class instead as that would be a more optimized approach

Yup, it would have destroyed animations. Now, I have just added the functionality of closing overlay when clicking the same link.

**Review by sohamjaiswal — APPROVED** [review]
lgtm 👍

good job

**Pull request merged**
